on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

name: Publish latest images

jobs:
  build:
    name: publish latest
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: actions/checkout@v2
    - uses: imjasonh/setup-ko@v0.4
    - run: ko publish --base-import-paths ./cmd/...
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v1
    - id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository }}/base
        flavor: |
          latest=auto
    - uses: docker/build-push-action@v2
      with:
        push: true
        context: ./images/base
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
